urls.py
from django.contrib import admin
from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
from django.views.generic.simple import direct_to_template, redirect_to
from djforms.core.views import data_entered
from djforms.auth.views import loggedout

#import authority

admin.autodiscover()
#authority.autodiscover()

handler404 = 'djforms.core.views.four_oh_four_error'
handler500 = 'djforms.core.views.server_error'

urlpatterns = patterns('',
    # home
    (r'^$', direct_to_template, {'template': 'forms_home.html'}),
    # LIS
    (r'^lis/', include('djforms.lis.urls')),
    # django authoriity
    #(r'^authority/', include('authority.urls')),
    # CSV
    (r'^admin/(?P<app_label>[\d\w]+)/(?P<model_name>[\d\w]+)/csv/', 'djforms.core.util.admin_list_export'),
    #(r'^admin/', include(admin.site.urls)),
    (r'^admin/', admin.site.urls),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # for the maintenance/evs form environment
    (r'^maintenance/', include('djforms.maintenance.urls')),
    # for the alumni forms
    (r'^alumni/', include('djforms.alumni.urls')),
    # for the alumni forms
    (r'^biology/', include('djforms.biology.urls')),
    # CharacterQuest
    (r'^character-quest/', include('djforms.characterquest.urls')),
    # generic request complete
    (r'^success/$', 'djforms.core.views.data_entered'),
    # for the job post environment
    (r'^job/', include('djforms.jobpost.urls')),
    # office of the president forms
    (r'^president/', include('djforms.president.urls')),
    # for the security appeal form environment
    (r'^security/', include('djforms.security.urls')),
    # sustainability forms
    (r'^sustainability/', include('djforms.sustainability.urls')),
    # for the video forms
    (r'^video/', include('djforms.video.urls')),
    # for the modern language form environment
    (r'^languages/', include('djforms.languages.urls')),
    # admissions
    (r'^admissions/', include('djforms.admissions.urls')),
    # polisci
    (r'^political-science/', include('djforms.polisci.urls')),
    # writing across curriculum
    (r'^writingcurriculum/', include('djforms.writingcurriculum.urls')),
    # auth
    url(r'^accounts/login',auth_views.login,{'template_name': 'accounts/login.html'},name='auth_login'),
    url(r'^accounts/logout/$',auth_views.logout,{'next_page': '/forms/accounts/loggedout/'}),
    url(r'^accounts/loggedout',loggedout,{'template_name': 'accounts/logged_out.html'}),
    url(r'^accounts/$', redirect_to, {'url': '/forms/', 'permanent': True}),
)

roomform/reserve/forms.py
from django import forms
from djforms.widgets import *
STATUS_CHOICES=[('', '---------- pick one ----------'),
                ('Trustee', 'Trustee'),
                ('Administration', 'Administration'),
                ('Faculty', 'Faculty'),
                ('Adjunct Faculty', 'Adjunct Faculty'),
                ('TLE', 'TLE'),
                ('Staff', 'Staff'),
                ('Graduate Student', 'Graduate Student'),
                ('Undergraduate Student', 'Undergraduate Student'),]
HOUR_CHOICES=[  (12, '12'),
                (1, '1'),
                (2, '2'),
                (3, '3'),
                (4, '4'),
                (5, '5'),
                (6, '6'),
                (7, '7'),
                (8, '8'),
                (9, '9'),
                (10, '10'),
                (11, '11'),]
MINUTE_CHOICES=[(0, '00'),
                (5, '05'),
                (10, '10'),
                (15, '15'),
                (20, '20'),
                (25, '25'),
                (30, '30'),
                (35, '35'),
                (40, '40'),
                (45, '45'),
                (50, '50'),
                (55, '55'),]
MERIDIEM_CHOICES=[  ('p.m.','p.m.'),
                    ('a.m.','a.m.'),]
ROOM_CHOICES=[  ('', '---------- pick one ----------'),
                ('Hedberg Library 105','Hedberg Library 105'),
                ('Hedberg Library 106','Hedberg Library 106'),
                ('Hedberg Library 107','Hedberg Library 107'),
                ('Hedberg Library 108','Hedberg Library 108'),
                ('Hedberg Library 109','Hedberg Library 109'),
                ('Hedberg Library 159','Hedberg Library 159'),
                ('Hedberg Library 162','Hedberg Library 162'),
                ('Hedberg Library 163','Hedberg Library 163'),
                ('Hedberg Library 164','Hedberg Library 164'),
                ('Hedberg Library 170','Hedberg Library 170'),
                ('Hedberg Library 172','Hedberg Library 172'),
                ('Hedberg Library 217','Hedberg Library 217'),
                ('Johnson Art Center 103','Johnson Art Center 103'),
                ('Johnson Art Center 117','Johnson Art Center 117'),
                ('Johnson Art Center 140','Johnson Art Center 140'),
                ('Johnson Art Center 142','Johnson Art Center 142'),
                ('Johnson Art Center 205','Johnson Art Center 205'),
                ('Johnson Art Center 207','Johnson Art Center 207'),
                ('Johnson Art Center 209','Johnson Art Center 209'),
                ('Johnson Art Center 215','Johnson Art Center 215'),
                ('Johnson Art Center 216','Johnson Art Center 216'),
                ('Johnson Art Center 219','Johnson Art Center 219'),
                ('Johnson Art Center 252','Johnson Art Center 252'),
                ('Johnson Art Center 253','Johnson Art Center 253'),
                ('Lentz Hall 200','Lentz Hall 200'),
                ('Lentz Hall 201','Lentz Hall 201'),
                ('Lentz Hall 202','Lentz Hall 202'),
                ('Lentz Hall 203','Lentz Hall 203'),
                ('Lentz Hall 220','Lentz Hall 220'),
                ('Lentz Hall 221','Lentz Hall 221'),
                ('Lentz Hall 222','Lentz Hall 222'),
                ('Lentz Hall 223','Lentz Hall 223'),
                ('Lentz Hall 224','Lentz Hall 224'),
                ('Lentz Hall 225','Lentz Hall 225'),
                ('Lentz Hall 227','Lentz Hall 227'),
                ('Lentz Hall 229','Lentz Hall 229'),
                ('Lentz Hall 230','Lentz Hall 230'),
                ('Lentz Hall 231','Lentz Hall 231'),
                ('Lentz Hall 233','Lentz Hall 233'),
                ('Lentz Hall 234','Lentz Hall 234'),
                ('Lentz Hall 300','Lentz Hall 300'),
                ('Lentz Hall 318','Lentz Hall 318'),
                ('Lentz Hall 319','Lentz Hall 319'),
                ('Lentz Hall 332','Lentz Hall 332'),
                ('Lentz Hall 337','Lentz Hall 337'),
                ('Lentz Hall 424','Lentz Hall 424'),
                ('Lentz Hall 425','Lentz Hall 425'),
                ('Lentz Hall 426','Lentz Hall 426'),
                ('Lentz Hall 432','Lentz Hall 432'),
                ('Lentz Hall Ahrens','Lentz Hall Ahrens'),
                ('Straz 106','Straz 106'),
                ('Straz 107','Straz 107'),
                ('Straz 109','Straz 109'),
                ('Straz 110','Straz 110'),
                ('Straz 111','Straz 111'),
                ('Straz 117','Straz 117'),
                ('Straz 119','Straz 119'),
                ('Straz 123','Straz 123'),
                ('Straz 125','Straz 125'),
                ('Straz 129','Straz 129'),
                ('Straz 210','Straz 210'),
                ('Straz 215','Straz 215'),
                ('Straz 218','Straz 218'),
                ('Straz 220','Straz 220'),
                ('Straz 223','Straz 223'),
                ('Straz 227','Straz 227'),
                ('Straz 233','Straz 233'),
                ('Straz B 4','Straz B 4'),
                ('Straz B12','Straz B12'),]
class RoomReserveForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField(label='Your e-mail')
    local_phone = forms.CharField(max_length=20)
    status = forms.ChoiceField(choices=STATUS_CHOICES)
    date = forms.DateField(widget=DateTimeWidget)
    start_time_hours = forms.ChoiceField(choices=HOUR_CHOICES)
    start_time_minutes = forms.ChoiceField(choices=MINUTE_CHOICES)
    start_time_meridiem = forms.ChoiceField(choices=MERIDIEM_CHOICES)
    start_time = forms.TimeField(required=False)
    end_time_hours = forms.ChoiceField(choices=HOUR_CHOICES)
    end_time_minutes = forms.ChoiceField(choices=MINUTE_CHOICES)
    end_time_meridiem = forms.ChoiceField(choices=MERIDIEM_CHOICES)
    end_time = forms.TimeField(required=False)
    room = forms.ChoiceField(ROOM_CHOICES)
    title_of_event = forms.CharField(required=False, max_length=50)
    department = forms.CharField(required=False, max_length=50)
    course_number = forms.CharField(required=False, max_length=25)
    additional_requests = forms.CharField(required=False, widget=forms.Textarea)
    comments = forms.CharField(required=False, widget=forms.Textarea)

    #Makes sure the user enters a first name
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name == 'Enter first name':
            raise forms.ValidationError("Enter a First Name!")
        return first_name
    
    #Makes sure the user enters a last name
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name == 'Enter last name':
            raise forms.ValidationError("Enter a Last Name!")
        return last_name
    
    #Makes sure the user enters a phone number
    def clean_local_phone(self):
        local_phone = self.cleaned_data['local_phone']
        if local_phone == 'Enter phone number':
            raise forms.ValidationError("Enter a Phone Number!")
        return local_phone
    
    #Makes sure the user picks a date later than today
    def clean_date(self):
        date = self.cleaned_data['date']
        if date <= datetime.date.today():
            raise forms.ValidationError("You must pick a date after today!")
        return date
    
    def clean_start_time(self):
        #assign proper data
        start_time = self.cleaned_data['start_time']
        start_time_meridiem = self.cleaned_data['start_time_meridiem']
        start_time_hours = int(self.cleaned_data['start_time_hours'])
        start_time_minutes = int(self.cleaned_data['start_time_minutes'])
        #convert the time to seconds
        start_time = ( start_time_hours * 3600 ) + ( start_time_minutes * 60 )
        return start_time
        
    def clean_end_time(self):
        #assign proper data, we need start time stuff for validation comparison
        start_time = self.cleaned_data['start_time']
        start_time_meridiem = self.cleaned_data['start_time_meridiem']
        start_time_hours = int(self.cleaned_data['start_time_hours'])
        end_time = self.cleaned_data['end_time']
        end_time_meridiem = self.cleaned_data['end_time_meridiem']
        end_time_hours = int(self.cleaned_data['end_time_hours'])
        end_time_minutes = int(self.cleaned_data['end_time_minutes'])
        #set the time to the proper amount of seconds
        end_time = (end_time_hours * 3600) + ( end_time_minutes * 60 )
        end_time2 = end_time
        #compare the two based on seconds and meridiem
        if start_time_meridiem == 'p.m.' and end_time_meridiem == 'a.m.':
            raise forms.ValidationError("Your end time must remain in the same day as your start time!")
        if start_time_meridiem == end_time_meridiem:
            if start_time_hours == 12:
                start_time = start_time - 43200
            if end_time_hours == 12:
                end_time2 = end_time2 - 43200
            if end_time2 <= start_time:
                raise forms.ValidationError("Your end time must come after your start time!")
        return end_time

templates/equipmentform/equipment_form.html
{% extends "base.html" %}
{% block title %}LIS Equipment Reservations{% endblock %}
{% block extra_javascript %}
    <script src="http://www.carthage.edu/assets/js/jquery/ui/ui.datepicker.min.js"></script>
    <script src="http://www.carthage.edu/assets/js/jquery/plugins/jquery.ptTimeSelect.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
        $("#id_date").datepicker({firstDay:0,appendText:"(format mm/dd/yyyy)",changeFirstDay:false,dateFormat:"mm/dd/yy",showOn:"both",buttonImage: "http://www.carthage.edu/assets/img/ico/calendar.gif",buttonImageOnly:true});
        $('#id_start_time').ptTimeSelect();
        $('#id_end_time').ptTimeSelect();
        });
    </script>
{% endblock %}
{% block extra_style %}
    <link href="http://www.carthage.edu/assets/css/jquery/ui/datepicker/ui.datepicker.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/css/jquery/ui/ui.core.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/css/jquery/ui/ui.theme.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/css/jquery/plugins/jquery.ptTimeSelect.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/current/css/plugins/forms.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/current/css/overrides/forms.css" rel="stylesheet" type="text/css" />
    <link href="http://www.carthage.edu/assets/current/css/overrides/forms.bridge.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        #ptTimeSelectCntr {color: #303030;background: #ebebeb;font: .74em Arial, Verdana, sans-serif;text-align: center;line-height: 1.6em;margin: 2.5em 0;}
        .tab_content_container {
        width: 705px;
    </style>
{% endblock %}
{% block left_nav %}
    <div id="first">
    <ul class="sf-vertical" id="nav"><li><a href="http://www.carthage.edu/ais/">Library and Information Services</a></li><li><a href="http://www.carthage.edu/ais/library.cfm">Hedberg Library</a></li><li><a href="http://www.carthage.edu/ais/computer.cfm">Computer Center</a></li><li><a href="http://www.carthage.edu/ais/media.cfm">Media Services</a></li><li><a href="http://www.carthage.edu/ais/tutoring.cfm">Tutoring</a></li><li><a href="http://www.carthage.edu/ais/writing.cfm">Writing Center</a></li></ul>
    </div>
{% endblock %}
{% block content %}
<div class="buffer">
    <h1>Equipment Reservations</h1>
    <p>Click on the link below to reserve audio/visual equipment. </p>
    {% if form.errors %}
    <h2 style="color: red;">Please correct the error{{ form.errors|pluralize }} below.</h2>
    {% endif %}
    <form method="POST" action="." class="form">{% csrf_token %}
        <input type="hidden" id="id_next" name="next" value="{{ redirect }}" />
        <fieldset class="blockLabels">
            <ol>
                {% for field in form %}
                    <li class="ctrlHolder">
                    <h3{% if field.field.required %} class="required"{% endif %}>{{ field.label_tag }}</h3>
                    {% if field.errors %}
                        <div class="warning">
                        <span class="error-message">{{ field.errors|join:", "}}</span>
                    {% else %}
                        <div>
                    {% endif %}
                    {{field}}
                    {% if field.help_text %}
                        <p class="help">{{field.help_text}}</p>
                    {% endif %}
                    </div>
                </li>
                {% endfor %}
                <li class="btnHolder">
                    <label for="id_submit">&nbsp;&nbsp;</label>
                    <p>Submission of a request does NOT GUARANTEE your reservation.  You will receive a confirmation by email when your reservation has been entered.  Requests submitted with less than one full working day's advance notice may not be honored.</p>
                    <p>If this form is inadequate to meet your reservation needs, please contact Media Services directly at av@carthage.edu or (262)551-5950.</p>
                    <p>* Still digital cameras save to 3.5" floppy discs. Camcorders use miniDV tapes. Media Services does NOT provide discs or tapes for patron use.</p><br />
                    <p>** For use only by authorized CDM faculty and students.</p><br />
                    <input type="submit" value="Submit Request" class="button" />
                </li>
            </ol>
        </fieldset>
    </form>
</div>
{% endblock %}