djforms/core/urls.py
# -*- coding: utf-8 -*-

"""URLs for all views."""

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from djauth.views import loggedout
from djforms.core.util import admin_list_export

admin.autodiscover()

handler404 = 'djtools.views.errors.four_oh_four_error'
handler500 = 'djtools.views.errors.server_error'


urlpatterns = [
    # home
    path('', RedirectView.as_view(url='https://www.carthage.edu/bridge/')),
    # simple 400 error view
    path(
        'denied/',
        TemplateView.as_view(template_name='denied.html'),
        name='access_denied',
    ),
    # auth
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(),
        {'template_name': 'registration/login.html'},
        name='auth_login',
    ),
    path(
        'accounts/logout/',
        auth_views.LogoutView.as_view(),
        {'next_page': reverse_lazy('auth_loggedout')},
        name='auth_logout',
    ),
    path(
        'accounts/loggedout/',
        loggedout,
        {'template_name': 'registration/logged_out.html'},
        name='auth_loggedout',
    ),
    path('accounts/', RedirectView.as_view(url=reverse_lazy('auth_login'))),
    path(
        'denied/',
        TemplateView.as_view(template_name='denied.html'),
        name='access_denied',
    ),
    # CSV
    path(
        'rocinante/<str:app_label>/<str:model_name>/csv/',
        admin_list_export,
        name='admin_list_export',
    ),
    # admin
    path('rocinante/', include('loginas.urls')),
    path('rocinante/', admin.site.urls),
    # alumni
    path('alumni/', include('djforms.alumni.urls')),
    # music
    path('music/', include('djforms.music.urls')),
    # polisci
    path('political-science/', include('djforms.polisci.urls')),
    # celebration of scholars
    path('scholars/', include('djforms.scholars.urls')),
    # summernote wysiwyg
    path('summernote/', include('django_summernote.urls')),
    # writing across curriculum
    path('writingcurriculum/', include('djforms.writingcurriculum.urls')),
    # recaptcha
    path('captcha/', include('captcha.urls')),
]

djforms/scholars/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from django.views.generic import TemplateView

from djforms.scholars.views import presentation
from djforms.scholars.views import imprimir


urlpatterns = [
    # print
    path('presentation/print/', imprimir.alpha, name='presentation_print'),
    path(
        'presentation/alpha/', imprimir.alpha,
        {'template': 'scholars/print/alpha.html'},
        name='presentation_print_alpha',
    ),
    # archives
    path(
        'archives/<str:ptype>/<str:medium>/<str:year>/',
        presentation.archives,
        name='presentation_archives',
    ),
    path(
        'archives/<str:ptype>/<str:medium>/',
        presentation.archives,
        name='presentation_archives_home',
    ),
    # presentation crud
    path(
        'presentation/success/',
        TemplateView.as_view(template_name='scholars/presentation/done.html'),
        name='presentation_form_done',
    ),
    path(
        'presentation/manager/',
        presentation.manager,
        name='presentation_manager',
    ),
    path(
        'presentation/action/',
        presentation.action,
        name='presentation_action',
    ),
    path(
        'presentation/<int:pid>/update/',
        presentation.form,
        name='presentation_update',
    ),
    path(
        'presentation/<int:pid>/detail/',
        presentation.detail,
        name='presentation_detail',
    ),
    path('presentation/', presentation.home, name='presentation_home'),
    path(
        'presentation/form/',
        presentation.form,
        name='presentation_form',
    ),
    # send email to all presentation leaders
    # 10 Apr 2014: currently not completed
    #path(
    #    r'^presenters/email/leaders/$',
    #    presentation.email_leaders, name="email_leaders"
    #),
    # send email to a presentation's leader and sponsor
    path(
        'presenters/email/success/',
        TemplateView.as_view(template_name='scholars/presenters/email_done.html'),
        name='email_presenters_done',
    ),
    path(
        'presenters/email/all/',
        presentation.email_all_presenters,
        name='email_all_presenters',
    ),
    path(
        'presenters/email/<int:pid>/<str:action>/',
        presentation.email_presenters,
        name='email_presenters_form',
    ),
]

djforms/scholars/models.py
# -*- coding: utf-8 -*-

import json
import requests

from django.conf import settings
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from djforms.core.models import BINARY_CHOICES
from djforms.core.models import Department
from djforms.core.models import YEAR_CHOICES
from djtools.fields import NOW
from djtools.utils.mail import send_mail
from taggit.managers import TaggableManager


ALLOWED_EXTENSIONS = (
    'pdf', 'PDF', 'png', 'PNG', 'jpg', 'JPG', 'jpeg', 'JPEG', 'heic', 'HEIC',
)
FILE_VALIDATORS = [
    FileExtensionValidator(allowed_extensions=ALLOWED_EXTENSIONS),
]

WORK_TYPES = (
    ('SURE', 'SURE'),
    ('Senior thesis', 'Senior thesis'),
    ('Independent research', 'Independent research'),
    ('Course project', 'Course project'),
    ("Master's thesis", "Master's thesis"),
)
PRESENTER_TYPES = (
    ('', '----select----'),
    ('Student', 'Student'),
    ('Faculty', 'Faculty'),
    ('Staff', 'Staff'),
)
PRESENTATION_CHOICES = (
    ('Poster Presentation', "Poster Presentation"),
    ('Oral Presentation', "Oral Presentation"),
)
YEAR = NOW.year


class Person(object):
    """
    Dynamic 'person' object.

    Usage:

    data = {"name":"larry","email":"larry@carthage.edu"}
    p = Person(**data)
    p.id = 90125
    etc
    """

    def __init__(self, **entries):
        """Initialization method."""
        self.__dict__.update(entries)


def get_json(yuri):
    """Obtain the json data from directory API."""
    jason = cache.get('{0}_api_json'.format(yuri))
    if jason is None:
        # read the json data from URL
        earl = "{0}{1}/api/json.txt?api_key={2}".format(
            settings.API_PEOPLE_URL, yuri, settings.API_KEY,
        )
        response =  requests.get(earl)
         #jason_data = json.loads(response.text)
        #data = response.read()
        # json doesn't like trailing commas, so...
        #data = data.replace(',]', ']')
        data = response.text
        jason = json.loads(response.text)
        cache.set('{0}_api_json'.format(yuri), jason)
    return jason


def get_people(yuri):
    """Obtain the group of people from the directory API."""
    people = cache.get('{0}_api_objects'.format(yuri))
    if people is None:
        jason = get_json(yuri)
        people = {}
        for jay in jason:
            person = Person(**jay)
            people[person.id] = person
        cache.set('{0}_api_objects'.format(yuri), people)
    return people


class Presenter(models.Model):
    """Data model class for the presenter."""

    date_created = models.DateTimeField("Date Created", auto_now_add=True)
    date_updated = models.DateTimeField("Date Updated", auto_now=True)
    college_id = models.CharField(max_length=8, null=True, blank=True)
    first_name = models.CharField(max_length=128, null=True, blank=True)
    last_name = models.CharField(max_length=128, null=True, blank=True)
    email = models.CharField(max_length=128, null=True, blank=True)
    leader = models.BooleanField("Presentation leader", default=False)
    prez_type = models.CharField(
        "Presenter type",
        max_length=16,
        choices=PRESENTER_TYPES,
        null=True,
        blank=True,
    )
    college_year = models.CharField(
        "Current year at Carthage",
        max_length=1,
        choices=YEAR_CHOICES,
        null=True,
        blank=True,
    )
    major = models.CharField(max_length=128, null=True, blank=True)
    hometown = models.CharField(max_length=128, null=True, blank=True)
    sponsor = models.CharField(max_length=128, null=True, blank=True)
    sponsor_name = models.CharField(max_length=128, null=True, blank=True)
    sponsor_email = models.CharField(max_length=128, null=True, blank=True)
    sponsor_other = models.CharField(max_length=255, null=True, blank=True)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    mugshot = models.ImageField(
        max_length=255,
        upload_to="files/scholars/mugshots",
        help_text="75 dpi and .jpg only",
    )
    ranking = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        """Default value for the objects."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        """Override the save() method to update some things first."""
        if self.sponsor:
            sid = int(self.sponsor)
            faculty = get_people("faculty")
            try:
                self.sponsor_name = '{0} {1}'.format(
                    faculty[sid].firstname,
                    faculty[sid].lastname,
                )
                self.sponsor_email = faculty[sid].email
            except Exception:
                self.sponsor_name = None
                self.sponsor_email = None
        super(Presenter, self).save()

    def year(self):
        """Deal with academic years."""
        if self.college_year:
            year = YEAR_CHOICES[int(self.college_year)][1]
        else:
            year = None
        return year

    def presenter_type(self):
        """Display the presenter type."""
        return PRESENTOR_TYPES[self.prez_type][1]


class Presentation(models.Model):
    """Data model class for the presentation."""

    user = models.ForeignKey(
        User,
        verbose_name="Created by",
        related_name='presentation_created_by',
        on_delete=models.CASCADE,
    )
    updated_by = models.ForeignKey(
        User,
        verbose_name="Updated by",
        related_name='presentation_updated_by',
        editable=False,
        on_delete=models.CASCADE,
    )
    date_created = models.DateTimeField("Date Created", auto_now_add=True)
    date_updated = models.DateTimeField("Date Updated", auto_now=True)
    ranking = models.IntegerField(null=True, blank=True, default=0)
    title = models.CharField("Presentation title", max_length=255)
    reviewer = models.CharField(max_length=128, null=True, blank=True)
    leader = models.ForeignKey(
        Presenter,
        verbose_name="Presentation leader",
        related_name='presentation_leader',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    presenters = models.ManyToManyField(
        Presenter, related_name="presentation_presenters", blank=True,
    )
    funding = models.CharField(
        "Funding source (if applicable)",
        max_length=255,
        help_text="e.g. external funding, SURE, etc.",
        null=True,
        blank=True,
    )
    work_type = models.CharField(max_length=32, choices=WORK_TYPES)
    permission = models.CharField(
        "Permission to reproduce",
        max_length=3,
        choices=BINARY_CHOICES,
        help_text="""
            Do you grant Carthage permission to reproduce your presentation?
        """,
    )
    shared = models.CharField(
        "Faculty sponsor approval",
        max_length=3,
        choices=BINARY_CHOICES,
        help_text="""
            Has your faculty sponsor approved your proposal?
            Note: Faculty and staff presenters should choose 'yes'.
        """,
    )
    abstract_text = models.TextField(
        "Abstract",
        help_text="Copy and paste your abstract text or start typing.",
    )
    presentation_type = models.CharField(max_length=32, choices=PRESENTATION_CHOICES)
    need_table = models.CharField(max_length=3, choices=BINARY_CHOICES)
    need_electricity = models.CharField(max_length=3, choices=BINARY_CHOICES)
    poster_file = models.FileField(
        upload_to='files/scholars/posters/{0}'.format(YEAR),
        validators=FILE_VALIDATORS,
        help_text="Upload a poster file",
        null=True,
        blank=True,
    )
    status = models.BooleanField(default=False)

    class Meta:
        """Sub-class for settings configurations about the parent class."""

        #ordering = ['date_created']
        get_latest_by = 'date_created'
        permissions = (('manage_presentation', 'manage presentation'),)

    def __str__(self):
        """Display the default value."""
        return self.title

    def save(self, *args, **kwargs):
        """Override the save() method to update some things first."""
        # send email if approved
        if self.pk is not None:
            prez = Presentation.objects.get(pk=self.pk)
            if (prez.status != self.status) and self.status:
                if settings.DEBUG:
                    TO_LIST = [settings.SERVER_EMAIL]
                else:
                    TO_LIST = [self.user.email,]
                email = settings.DEFAULT_FROM_EMAIL
                subject = '[Celebration of Scholars] Presentation has been approved'
                send_mail(
                    None,
                    TO_LIST,
                    subject,
                    email,
                    'scholars/presentation/approved_mail.html',
                    self,
                    reply_to=[email,],
                    bcc=[settings.MANAGERS[0][1],],
                )
        else:
            self.updated_by = self.user
        super(Presentation, self).save()

    def get_absolute_url(self):
        """Return the default URL."""
        return reverse('presentation_detail', kwargs={'pid': self.id})

    def get_update_url(self):
        """Return the update URL."""
        return reverse('presentation_update', kwargs={'pid': self.id})

    def get_presenters(self):
        """Obtain all presenters for this presentation."""

djforms/scholars/views/imprimir.py
# -*- coding: utf-8 -*-

import datetime
import os

from django.shortcuts import render
from djforms.scholars.models import Presentation


NOW  = datetime.datetime.now()
YEAR = int(NOW.year)


def alpha(request, template=None):
    presentations = Presentation.objects.filter(
        date_created__year=YEAR,
    ).filter(status=True).order_by('leader__last_name')
    if not template:
        template = 'scholars/print/pdf.html'
    return render(request, template, {'presentations': presentations})

djforms/scholars/views/print.py
from django.shortcuts import render_to_response
from django.template import RequestContext, loader

from djforms.scholars.models import Presentation

import datetime, os

NOW  = datetime.datetime.now()
YEAR = int(NOW.year)

def alpha(request, template=None):
    p = Presentation.objects.filter(date_updated__year=YEAR)
    presentations = p.order_by('leader__last_name')

    if not template:
        template = "scholars/print/pdf.html"
    return render_to_response (
        template, {"presentations": presentations,},
        context_instance=RequestContext(request)
    )

djforms/templates/scholars/presentation/action_form.inc.html
<div class="fright">
    <form action="{% url 'presentation_action' %}" method="post" class="form">{% csrf_token %}
    <input type="hidden" name="pid" value="{% if p.id %}{{p.id}}{% else %}{{pid}}{% endif %}" />
    <select name="action">
        <option value="">---Select an action---</option>
        <option value="update">Update presentation</option>
        <option value="email">Email presentation leaders</option>
        <option value="reject">Rejection Email</option>
    </select>
    <input type="submit" class="button" value="Go" />
    </form>
</div>

djforms/templates/scholars/presentation/approved_mail.html
<!DOCTYPE HTML>
<html>
<head>
<style type="text/css">
body {font-size:1.1em;font-family:verdana, arial, sans-serif;}
{% include "scholars/presentation/screen.css" %}
.presentation {margin-bottom:30px;page-break-after:always;}
.presentation .title {font-weight:bold;font-size:1.5em; border-top:1px solid #000; }
.presentation .text {display:block;}
.person {display: block;font-size: 10pt;margin-bottom:10pt;page-break-inside: avoid;page-break-before: auto;page-break-after: auto;}
.personmain {page-break-inside:avoid;column-break-after:avoid;}
.mugshot {display:block; float:left;margin-right:7px;margin-bottom:7px; width:100px; }
.name {font-weight:bold;font-size: 10pt;}
.work-type p, .requirements p, .funding p, .absbract p {font-size:1.3em;font-weight:bold;}
.work-type p span {font-size:1.1em;font-weight:normal;}
</style>
</head>
<body>
<h1>Approved</h1>
<p>Your Celebration of Scholars presentation:</p>
<p class="title">{{data.title}}</p>
<p>has been approved.</p>
<p><a href="https://app.carthage.edu{% url 'presentation_detail' data.id %}">View Presentation</a></p>
<h2>Next Step</h2>
<p>Create and upload your poster file.</p>
</body>
</html>

djforms/templates/scholars/presentation/archives_print.html
<!DOCTYPE html>
{% autoescape off %}
<html>
<head>
    <title>Celebration of Scholars Print</title>
    <link href="/static/forms/css/scholars/print.css" rel="stylesheet" />
</head>
<body>
    {% for p in prez %}
        {% include "scholars/presentation/detail_data.inc.html" %}
    {% endfor %}
</body>
</html>
{% endautoescape %}

djforms/templates/scholars/presentation/archives_screen.html
{% extends "scholars/presentation/home.html" %}
{% block title %}
  Presentation Archives {{year}} &mdash;
  Celebration of Scholars &mdash;
  Carthage College
{% endblock %}
{% block extra_javascript %}
{{block.super}}
<script src="//www.carthage.edu/static/vendor/jquery/plugins/tablesorter/jquery.tablesorter.min.js"
  type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
  $(function() {
    $("#presentation_list_table").tablesorter(
      {widgets: ['zebra'],headers:{3:{sorter:false}}}
    );
  });
</script>
{% endblock %}
{% block extra_style %}
{{block.super}}
<link href="//www.carthage.edu/static/vendor/jquery/plugins/tablesorter/style.css"
  type="text/css" rel="stylesheet" />
<style>
  table.tablesorter { width: 100%; }
  td, th {padding:5px;vertical-align:top;}
  table.tablesorter tbody tr.odd td { background-color: #efefef; }
</style>
{% endblock %}
{% block content %}
  <h3>{{year}}</h3>
  <table id="presentation_list_table" class="tablesorter">
  <thead>
  <tr>
    <th style="width:20px;">&nbsp;</th>
    <th width="350">Title</th>
    <th width="150">Lead Presenter</th>
  </tr>
  </thead>
  {% for p in prez %}
    <tr class="{% cycle 'odd' 'even' %}">
      <td>{{forloop.counter}}</td>
      <td><a href="{{p.get_absolute_url}}">{{p.title}}</a></td>
      <td>{{p.leader.last_name}}, {{p.leader.first_name}}</td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

djforms/templates/scholars/presentation/detail.html
{% extends "scholars/presentation/home.html" %}
{% block title %}
    {{p.title}} &mdash;
    Presentation Detail &mdash;
    Celebration of Scholars &mdash;
    Carthage College
{% endblock %}
{% block extra_javascript %}
<script type="text/javascript">
{{block.super}}
$(function() {
    $('#print h2').prepend('<a href="#print">Print</a>');
    $('#print h2 a').click(function() {
        window.print();
        return false;
    });
});
</script>
{% endblock %}
{% block extra_style %}
{{block.super}}
<style type="text/css">
  {% include "scholars/presentation/screen.css" %}
</style>
{% endblock %}
{% block content %}
  {% if manager %}
    {% include "scholars/presentation/action_form.inc.html" %}
  {% endif %}
  {% include "scholars/presentation/detail_data.inc.html" %}
{% endblock %}

djforms/templates/scholars/presentation/form.html
{% extends "scholars/presentation/home.html" %}
{% block title %}
    Presentation Form &mdash;
    Celebration of Scholars &mdash;
    Carthage College
{% endblock %}
{% block extra_javascript %}
  {{block.super}}
    <script src="//www.carthage.edu/static/vendor/jquery/plugins/jHtmlArea/jHtmlArea-0.8.min.js"
        type="text/javascript" charset="utf-8"></script>
    <script src="https://malsup.github.io/min/jquery.blockUI.min.js"
        type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $("#id_abstract_text").htmlarea({
                toolbar: [
                    "html","bold", "italic", "underline", "superscript",
                    "subscript", "|", "h1", "h2", "h3", "h4", "|", "indent",
                    "outdent", "horizontalrule", "link", "unlink", "|",
                    "orderedList", "unorderedList"
                ]
            });
            $("#id_poster_file").parent().css({
                'backgroundColor' : '#fff6bf',
                "border-color": "#ffd324",
                "border-width":"1px",
                "border-style":"solid"
            });
            var copies = {{copies}};
            // copy duplicate master for new presenter
            $("#clone").click(function () {
                copies++;
                newId = "doop_" + copies;
                $("#doopmaster").clone().attr("id",newId).appendTo("#duplicates");
                $.growlUI('Number of Presenters: ', copies);
            });
            // flag presenters that have a mugshot for upload.
            // cgi on the backend does not include empty filefields in []
            // hidden field name = "mugshoth"
            $("#duplicates").on('change', ".mugshot", function() {
                $(this).next(':hidden').val("True");
            });
            // remove presenter
            $('#duplicates').on("click", ".destroy_school", function() {
                if (copies > 0) {
                    copies--;
                    $(this).parent().remove();
                    $.growlUI('Number of Presenters: ', copies);
                }else{
                    $.growlUI('Warning', 'No presenters to delete');
                }
            });
            // switch for faculty/staff vs student
            $("#duplicates").on('change', "select[name='prez_type[]']", function () {
                if ( $(this).val()=="Student" ) {
                    $(this).parent().nextAll('.student:first').addClass("shown");
                    $(this).parent().nextAll('.facstaff:first').removeClass("shown");
                } else {
                    $(this).parent().nextAll('.facstaff:first').addClass("shown");
                    $(this).parent().nextAll('.student:first').removeClass("shown");
                }
            });
            $( "#presentation" ).submit(function( event ) {
                var error = false;
                $("div[id^='doop_']").each(function() {
                    var prez_type_obj = $(this).find('select[name="prez_type[]"]');
                    var prez_type = prez_type_obj.val();
                    if (prez_type) {
                        prez_type_obj.removeClass("error");
                    }
                    if ( prez_type == "Student" ) {
                        // Students
                        $(this).find(":input").each(function () {
                            if (this.name != "department[]" && this.name != "sponsor_other[]" && this.name != "leader[]" && this.name != "mugshot[]") {
                                if (this.name == "mugshoth[]") {
                                    if ( this.value == '') {
                                        $(this).prev().addClass("error");
                                        error = true;
                                    }else{
                                        $(this).prev().removeClass("error");
                                    }
                                }else if (!this.value) {
                                    $(this).addClass("error");
                                    error = true;
                                }else{
                                    $(this).removeClass("error");
                                }
                            }
                        });
                    } else if ( prez_type == "Faculty" || prez_type == "Staff" ) {
                        // Faculty or Staff
                        $(this).find(":input").each(function () {
                            console.log(this.name, this.value);
                            if (this.name == "department[]" || this.name == "first_name[]" || this.name == "last_name[]" || this.name == "prez_type[]" || this.name == "mugshoth[]") {
                                if (this.name == "mugshoth[]") {
                                    if ( this.value == '') {
                                        $(this).prev().addClass("error");
                                        error = true;
                                    }else{
                                        $(this).prev().removeClass("error");
                                    }
                                }else if (!this.value) {
                                    $(this).addClass("error");
                                    error = true;
                                }else{
                                    $(this).removeClass("error");
                                }
                            }
                        });
                    } else {
                        prez_type_obj.addClass("error");
                        error = true;
                    }
                });
                if (error) {
                    return false;
                }
            });
        });
    </script>
{% endblock %}
{% block extra_style %}
  {{block.super}}
  <link href="//www.carthage.edu/static/vendor/jquery/plugins/jHtmlArea/jHtmlArea.css"
    rel="stylesheet" type="text/css">
  <style type="text/css">
    div.jHtmlArea .ToolBar {width: 470px !important; }
    div.jHtmlArea .ToolBar ul li a.custom_disk_button
    {
        background: url(/static/forms/css/disk.png) no-repeat;
        background-position: 0 0;
    }
    div.jHtmlArea {
        width:500px !important;border: solid 1px #ccc; background: #efefef;
    }
    iframe {
        width:500px !important;height:300px !important;background: #fff;
        border: solid 1px #ccc;
    }
    #doopmaster {display: none;}
    div.growlUI {
        background: url(https://app.carthage.edu/media/djforms/img/ico/information.png) no-repeat 10px 10px;
    }
    div.growlUI h1, div.growlUI h2 {
        font-size: 1.4em; color: white; padding: 5px 5px 5px 75px;
        text-align: left;
    }
    .form input[type=text] {width: 350px;}
    .form input[type=file] {width: 200px;}
    .form input.tiny {margin:0;width:30px;vertical-align:middle;}
    .form input.small {margin:0;width:100px;vertical-align:middle;}
    .form input.medium {margin:0;width:150px;}
    .form input.large {margin:0;width:250px;}
    .form .blockLabels label {display: inline;}
    .form p {margin-bottom:0 !important;}
    .ctrlcx {float:right;width:25px;}
    .presenter {
        border: 1px solid #FFD324; border-radius: 3px 3px 3px 3px;
        box-shadow: 0 1px 0 #FFFFFF inset; margin: 0 auto 8px;
        padding: 6px 8px; background-color:#FFF6BF;
    }
    .hidden {display:none;}
    .facstaff {display:none;}
    .student {display:none;}
    .shown {display:block;}
    .mtop {margin-top:9px;}
    .fleft{width:265px;}
    dl dt { background: none;padding:0;}
  </style>
{% endblock %}
{% block content %}
<div class="forms-container">
  {% if manager and presentation %}
    {% include "scholars/presentation/action_form.inc.html" %}
  {% endif %}
  <h2>Presentation Form</h2>
  {% include "includes/required_text.html" %}
  {% include "includes/errors_text.html" %}
  <form method="post" action="." class="form" id="presentation" enctype="multipart/form-data">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    <fieldset class="blockLabels">
      <ol>
        {% for field in form.visible_fields %}
            {% if field.name == "poster_file" %}
                {% if presentation.status %}
                    {% include "form_field.inc.html" %}
                {% endif %}
            {% else %}
                {% include "form_field.inc.html" %}
            {% endif %}
        {% endfor %}
        {% if manager %}
        <li class="ctrlHolder">
            <h3><label>Status</label></h3>
            <p class="help">
            <input type="checkbox" id="id_status" name="status"
                {% if presentation.status %} checked="checked"{% endif %} />
            Is this presentation complete?
            </p>
        </li>
        {% endif %}
      </ol>
    </fieldset>
    <fieldset class="blockLabels">
      <ol>
        <li class="ctrlHolder">
            <div id="doopmaster" class="presenter">
                <img class="destroy_school fright"
                    src="/static/djforms/img/ico/silk/icons/delete.png"
                    title="Remove Presenter" alt="Remove Presenter">
                {% include "scholars/presentation/presenters.inc.html" %}
            </div>
            <h3><label>Presenters</label></h3>
        </li>
        <li style="margin-top:10px;">
            <div>
                Click on the
                <img style="margin-bottom:-3px;" src="/static/djforms/img/ico/silk/icons/add.png">
                symbol to add more presenters. Click on the
                <img style="margin-bottom:-3px;" src="/static/djforms/img/ico/silk/icons/delete.png">
                icon to remove presenters.
            </div>
            <p>
                <strong>NOTE</strong>:
                Photos must be JPEG format and must be high
                resolution&mdash;at least 300 DPI.
            </p>
            <p style="float:left;">
                <strong class="help">All fields are required.</strong>
            </p>
            <div class="ctrlcx">
                <img id="clone" src="/static/djforms/img/ico/silk/icons/add.png">
            </div>
        </li>
        <li class="ctrlHolder" id="duplicates">
            {% for p in presenters %}
            <div id="doop_{{forloop.counter}}" class="presenter">
                {% if forloop.counter != 1 %}
                <img class="destroy_school fright"
                    src="/static/djforms/img/ico/silk/icons/delete.png"
                    title="Remove Presenter" alt="Remove Presenter">
                {% else %}
                <div style="height:15px;width:15px;float:right;">
                    &nbsp;
                </div>
                {% endif %}
                {% include "scholars/presentation/presenters.inc.html" %}
            </div>
            {% endfor %}
        </li>
      </ol>
    </fieldset>
    {% include "form_submit.inc.html" %}
  </form>
</div>
{% endblock %}
{% block sidebar %}
  {% include "scholars/side_bar.html" %}
{% endblock %}